import React, { useState, useEffect } from 'react';
import api from '../services/api';
import { Bell, CheckCircle2, AlertCircle, Syringe, Pill, Info } from 'lucide-react';
import styles from './Notifications.module.css';

export default function Notifications() {
  const [notifications, setNotifications] = useState([]);
  const [unreadOnly, setUnreadOnly] = useState(false);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchNotifications();
  }, [unreadOnly]);

  const fetchNotifications = async () => {
    setLoading(true);
    try {
      const res = await api.get(`/notifications?unread_only=${unreadOnly}`);
      setNotifications(res.data);
    } catch (err) {
      console.error('Failed to load notifications:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleMarkRead = async (id) => {
    try {
      await api.patch(`/notifications/${id}/read`);
      fetchNotifications();
    } catch (err) {
      console.error('Error marking as read:', err);
    }
  };

  const getIcon = (type) => {
    switch (type) {
      case 'vaccination_due': return <Syringe size={20} color="var(--accent-pink)" />;
      case 'medication_reminder': return <Pill size={20} color="var(--accent-teal)" />;
      case 'health_alert': return <AlertCircle size={20} color="var(--status-error)" />;
      default: return <Info size={20} color="var(--primary)" />;
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <div>
          <h1>Reminders & Notifications</h1>
          <p>Proactive health alerts generated by your Health Reminder Agent.</p>
        </div>

        <div className={styles.filterToggle}>
          <label>
            <input
              type="checkbox"
              checked={unreadOnly}
              onChange={(e) => setUnreadOnly(e.target.checked)}
            />
            Show Unread Only
          </label>
        </div>
      </div>

      <div className="glass-card" style={{ padding: '1.75rem' }}>
        {loading ? (
          <p className={styles.statusMsg}>Loading notifications...</p>
        ) : notifications.length > 0 ? (
          <div className={styles.list}>
            {notifications.map((n) => (
              <div
                key={n.id}
                className={`${styles.card} ${n.is_read ? styles.read : styles.unread}`}
              >
                <div className={styles.iconBox}>{getIcon(n.type)}</div>

                <div className={styles.content}>
                  <div className={styles.topRow}>
                    <span className={styles.typeTag}>{n.type.replace('_', ' ')}</span>
                    <span className={styles.time}>
                      {new Date(n.created_at).toLocaleString([], {
                        month: 'short',
                        day: 'numeric',
                        hour: '2-digit',
                        minute: '2-digit',
                      })}
                    </span>
                  </div>
                  <p className={styles.msg}>{n.message}</p>
                </div>

                {!n.is_read && (
                  <button
                    onClick={() => handleMarkRead(n.id)}
                    className={styles.readBtn}
                    title="Mark as Read"
                  >
                    <CheckCircle2 size={18} /> Mark Read
                  </button>
                )}
              </div>
            ))}
          </div>
        ) : (
          <div className={styles.empty}>
            <Bell size={36} color="var(--text-dim)" />
            <p>No notifications to display.</p>
          </div>
        )}
      </div>
    </div>
  );
}
